syntax = "proto3";

package icw.core.biz;

option go_package = "icw_common/gen/core/biz;bizpb";

import "core/biz/common.proto";

// DeleteProjectThumbnail 请求结构体
message DeleteProjectThumbnailRequest {
  uint64 user_id = 1;
  uint64 project_id = 2;
}

// DeleteProjectThumbnail 响应结构体
message DeleteProjectThumbnailResponse {}

// GetProjectProfile 请求结构体
message GetProjectProfileRequest {
  uint64 user_id = 1;
  uint64 project_id = 2;
}

// GetProjectProfile 响应结构体
message GetProjectProfileResponse {
  Project project = 1;
}

// GetProjectThumbnail 请求结构体
message GetProjectThumbnailRequest {
  uint64 user_id = 1;
  uint64 project_id = 2;
}

// GetProjectThumbnail 响应结构体
message GetProjectThumbnailResponse {
  string thumbnail_url = 1;
}

// UpdateProjectProfile 请求结构体
message UpdateProjectProfileRequest {
  uint64 user_id = 1;
  uint64 project_id = 2;
  string name = 3;
  string building_name = 4;
  string building_location = 5;
  uint32 built_year = 6;
  string building_description = 7;
  string known_issues = 8;
  string assessment_goal = 9;
}

// UpdateProjectProfile 响应结构体
message UpdateProjectProfileResponse {
  Project project = 1;
}

// UploadProjectThumbnail 请求结构体
message UploadProjectThumbnailRequest {
  uint64 user_id = 1;
  uint64 project_id = 2;
  string content_type = 3;
}

// UploadProjectThumbnail 响应结构体
message UploadProjectThumbnailResponse {
  string upload_url = 1;
}

// 基础信息服务
service ProjectProfileService {
  // 删除项目缩略图
  rpc DeleteProjectThumbnail(DeleteProjectThumbnailRequest) returns (DeleteProjectThumbnailResponse);
  // 获取项目基础信息
  rpc GetProjectProfile(GetProjectProfileRequest) returns (GetProjectProfileResponse);
  // 获取项目缩略图
  rpc GetProjectThumbnail(GetProjectThumbnailRequest) returns (GetProjectThumbnailResponse);
  // 更新项目基础信息
  rpc UpdateProjectProfile(UpdateProjectProfileRequest) returns (UpdateProjectProfileResponse);
  // 上传项目缩略图
  rpc UploadProjectThumbnail(UploadProjectThumbnailRequest) returns (UploadProjectThumbnailResponse);
}
