syntax = "proto3";

package icw.core.biz;

option go_package = "icw_common/gen/core/biz;bizpb";

import "core/biz/common.proto";

// ListProjectDetectionTasks 请求结构体
message ListProjectDetectionTasksRequest {
  uint64 user_id = 1;
  uint64 project_id = 2;
}

// ListProjectDetectionTasks 响应结构体
message ListProjectDetectionTasksResponse {
  repeated .icw.core.common.ProjectDetectionStatus tasks = 1;
}

// ReportClassificationResult 请求结构体
message ReportClassificationResultRequest {
  string task_uuid = 1;
  string image_uuid = 2;
  string status = 3;
  repeated string task_codes = 4;
  string error_message = 5;
}

// ReportClassificationResult 响应结构体
message ReportClassificationResultResponse {}

// ReportDetectionSummaryResult 请求结构体
message ReportDetectionSummaryResultRequest {
  string task_uuid = 1;
  string image_uuid = 2;
  string status = 3;
  string result_json = 4;
  string error_message = 5;
}

// ReportDetectionSummaryResult 响应结构体
message ReportDetectionSummaryResultResponse {}

// ReportReasoningResult 请求结构体
message ReportReasoningResultRequest {
  string task_code = 1;
  string task_uuid = 2;
  string image_uuid = 3;
  string status = 4;
  string result_json = 5;
  repeated ReasoningArtifactUploadResult artifacts = 6;
  string error_message = 7;
}

// ReportReasoningResult 响应结构体
message ReportReasoningResultResponse {}

// RetryProjectDetection 请求结构体
message RetryProjectDetectionRequest {
  uint64 user_id = 1;
  uint64 project_id = 2;
}

// RetryProjectDetection 响应结构体
message RetryProjectDetectionResponse {
  uint32 task_count = 1;
}

// StartProjectDetection 请求结构体
message StartProjectDetectionRequest {
  uint64 user_id = 1;
  uint64 project_id = 2;
}

// StartProjectDetection 响应结构体
message StartProjectDetectionResponse {
  uint32 task_count = 1;
}

// 智能检测 RPC 服务
service ProjectDetectionService {
  // 获取项目智能检测任务列表
  rpc ListProjectDetectionTasks(ListProjectDetectionTasksRequest) returns (ListProjectDetectionTasksResponse);
  // 上报图像检测分类结果
  rpc ReportClassificationResult(ReportClassificationResultRequest) returns (ReportClassificationResultResponse);
  // 上报图像检测总结结果
  rpc ReportDetectionSummaryResult(ReportDetectionSummaryResultRequest) returns (ReportDetectionSummaryResultResponse);
  // 上报图像检测推理结果
  rpc ReportReasoningResult(ReportReasoningResultRequest) returns (ReportReasoningResultResponse);
  // 重试项目智能检测
  rpc RetryProjectDetection(RetryProjectDetectionRequest) returns (RetryProjectDetectionResponse);
  // 启动项目智能检测
  rpc StartProjectDetection(StartProjectDetectionRequest) returns (StartProjectDetectionResponse);
}
