syntax = "proto3";

package icw.core.biz;

option go_package = "icw_common/gen/core/biz;bizpb";

import "activity/common.proto";

// ReportProjectSummaryResult 请求结构体
message ReportProjectSummaryResultRequest {
  uint64 project_id = 1;
  .icw.activity.DetectionStatus.Value status = 2;
  string result_json = 3;
  string error_message = 4;
}

// ReportProjectSummaryResult 响应结构体
message ReportProjectSummaryResultResponse {}

// 评估报告 RPC 服务
service ProjectReportService {
  // 上报项目总结结果
  rpc ReportProjectSummaryResult(ReportProjectSummaryResultRequest) returns (ReportProjectSummaryResultResponse);
}
