syntax = "proto3";

package icw.core.biz;

option go_package = "icw_common/gen/core/biz;bizpb";

import "core/biz/common.proto";

// ReportClassificationResult 请求结构体
message ReportClassificationResultRequest {
  string task_uuid = 1;
  string image_uuid = 2;
  string status = 3;
  repeated string task_codes = 4;
  string error_message = 5;
}

// ReportClassificationResult 响应结构体
message ReportClassificationResultResponse {}

// ReportReasoningResult 请求结构体
message ReportReasoningResultRequest {
  string task_code = 1;
  string task_uuid = 2;
  string image_uuid = 3;
  string status = 4;
  string result_json = 5;
  repeated ReasoningArtifact artifacts = 6;
  string error_message = 7;
}

// ReportReasoningResult 响应结构体
message ReportReasoningResultResponse {}

// 智能检测服务
service ProjectDetectionService {
  // 上报图像检测分类结果
  rpc ReportClassificationResult(ReportClassificationResultRequest) returns (ReportClassificationResultResponse);
  // 上报图像检测推理结果
  rpc ReportReasoningResult(ReportReasoningResultRequest) returns (ReportReasoningResultResponse);
}
