syntax = "proto3";

package icw.core.biz;

option go_package = "icw_common/gen/core/biz;bizpb";

// CreateSocketTicket 请求结构体
message CreateSocketTicketRequest {
  uint64 user_id = 1;
  uint64 project_id = 2;
  string project_code = 3;
  string socket_scope = 4;
}

// CreateSocketTicket 响应结构体
message CreateSocketTicketResponse {
  string ticket = 1;
  int64 expires_in = 2;
}

// ValidateSocketTicket 请求结构体
message ValidateSocketTicketRequest {
  string project_code = 1;
  string socket_scope = 2;
  string ticket = 3;
}

// ValidateSocketTicket 响应结构体
message ValidateSocketTicketResponse {}

// SocketService WebSocket 服务
service SocketService {
  // CreateSocketTicket 创建 WebSocket 连接票据
  rpc CreateSocketTicket(CreateSocketTicketRequest) returns (CreateSocketTicketResponse);
  // ValidateSocketTicket 校验 WebSocket 连接票据
  rpc ValidateSocketTicket(ValidateSocketTicketRequest) returns (ValidateSocketTicketResponse);
}
