syntax = "proto3";

package icw.core.biz;

option go_package = "icw_common/gen/core/biz;bizpb";

import "core/common.proto";

// DeleteAvatar 请求结构体
message DeleteAvatarRequest {
  uint64 user_id = 1;
  string email = 2;
}

// DeleteAvatar 响应结构体
message DeleteAvatarResponse {}

// GetAvatar 请求结构体
message GetAvatarRequest {
  uint64 user_id = 1;
  string email = 2;
}

// GetAvatar 响应结构体
message GetAvatarResponse {
  string avatar_url = 1;
  .icw.core.common.AvatarType.Value avatar_type = 2;
}

// UploadAvatar 请求结构体
message UploadAvatarRequest {
  uint64 user_id = 1;
  string email = 2;
  string content_type = 3;
}

// UploadAvatar 响应结构体
message UploadAvatarResponse {
  string upload_url = 1;
}

// 用户业务 RPC 服务
service UserService {
  // 删除用户自定义头像
  rpc DeleteAvatar(DeleteAvatarRequest) returns (DeleteAvatarResponse);
  // 获取用户头像
  rpc GetAvatar(GetAvatarRequest) returns (GetAvatarResponse);
  // 上传用户自定义头像
  rpc UploadAvatar(UploadAvatarRequest) returns (UploadAvatarResponse);
}
