syntax = "proto3";

package icw.core.api;

option go_package = "icw_common/gen/core/api;apipb";

import "core/common.proto";

// GetImageDetectionResult 请求结构体
message GetImageDetectionResultRequest {
  string project_id = 1;
  string image_uuid = 2;
}

// GetImageDetectionResult 响应结构体
message GetImageDetectionResultResponse {
  .icw.core.common.ProjectImage image = 1;
  string original_url = 2;
  .icw.core.common.ProjectDetectionStatus status = 3;
  repeated string task_codes = 4;
  .icw.core.common.ProjectDetectionCorrosionResult corrosion_result = 5;
  .icw.core.common.ProjectDetectionCrackResult crack_result = 6;
  .icw.core.common.ProjectDetectionStainResult stain_result = 7;
  .icw.core.common.ProjectDetectionFlatnessResult flatness_result = 8;
  .icw.core.common.ProjectDetectionSpallingResult spalling_result = 9;
  .icw.core.common.ProjectDetectionSummaryResult summary_result = 10;
}

// GetProjectDetectionTasks 请求结构体
message GetProjectDetectionTasksRequest {
  string project_id = 1;
}

// GetProjectDetectionTasks 响应结构体
message GetProjectDetectionTasksResponse {
  repeated .icw.core.common.ProjectDetectionStatus tasks = 1;
}

// RetryProjectDetection 请求结构体
message RetryProjectDetectionRequest {
  string project_id = 1;
}

// RetryProjectDetection 响应结构体
message RetryProjectDetectionResponse {
  uint32 task_count = 1;
}

// StartProjectDetection 请求结构体
message StartProjectDetectionRequest {
  string project_id = 1;
}

// StartProjectDetection 响应结构体
message StartProjectDetectionResponse {
  uint32 task_count = 1;
}
