syntax = "proto3";

package icw.core.api;

option go_package = "icw_common/gen/core/api;apipb";

// CreateSocketTicket 请求结构体
message CreateSocketTicketRequest {
  string project_id = 1;
  string scope = 2;
}

// CreateSocketTicket 响应结构体
message CreateSocketTicketResponse {
  string ticket = 1;
  int64 expires_in = 2;
}

// SetupWebSocket 请求结构体
message SetupWebSocketRequest {
  string project_id = 1; // 从 HTTP Query 获取
  string scope = 2; // 从 HTTP Query 获取
  string ticket = 3; // 从 HTTP Query 获取
}

// SetupWebSocket 响应结构体
message SetupWebSocketResponse {}
